### ISSUE TITLE
PieChart animation

### ISSUE THREAD

**Issue by idanlo** [JesperLekland/react-native-svg-charts#371]
`animate` prop does not affect the PieChart component and there is no animation - there are also no errors indicating that the animation doesn't work.

react-native-svg-charts version - 5.3.0

**Comment by tuur155** [comment]
This is solved by #261

**Comment by idanlo** [comment]
@tuur155 so how can I animate pie charts? That issue is not solved, it just addresses the reason why animations doesn't work for pie charts

**Comment by wmonecke** [comment]
Any ideas?

**Comment by tolik85** [comment]
> Any ideas?

Did you find a solution?

**Comment by Rohitsaxena** [comment]
Using Animated.View from react-native-reanimated fixed it for me.
I think this could help for you guys.

**Comment by IronTony** [comment]
@Rohitsaxena could you please write a small example please?
